### ISSUE TITLE
Wrong arch for windows builds

### ISSUE THREAD

**Issue by erwin-faceit** [MrCSharp22/hugo-vsts#1]
First of all, thank you for forking and fixing this addon.

Since version [v0.103.0](https://github.com/gohugoio/hugo/releases/tag/v0.103.0), the assets have been renamed to arch64 instead of 64bit. For Linux build, they still provide a 64bit filename, but that's not going to last long.

Could you please fix/change this addon so it supports the new assetname if the version is >= 0.103.0?

**Comment by MrCSharp22** [comment]
Thanks @erwin-faceit I'll try to get an update out for this soon.

**Comment by MrCSharp22** [comment]
@erwin-faceit this is fixed now. Version 1.0.6 is on the marketplace. Please make sure to pick 1.* from the task edit view.

**Comment by erwin-faceit** [comment]
Awesome, thanks for the quick solution!
